apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: alvarogstem/apacheags:bb90ea81eb3de3aa4e8717db686f010f322b4ad6
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: password
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"  # Limitar a 50% de la CPU (0.5 * 1000m)
            requests:
              cpu: "250m"  # Solicitar un mínimo de 25% de la CPU (0.25 * 1000m)
          volumeMounts:
            - name: apache-data
              mountPath: /usr/local/apache2/htdocs
      volumes:
        - name: apache-data
          emptyDir: {}